### PR TITLE
Refactor and fix scrolling - except padding

### LINKED ISSUE #1873: Scrolling to annotations (by clicking on the annotation card) is [partially] broken
When the user clicks on an annotation card in the sidebar, the document scrolls to reveal to corresponding highlight. (Just like when the user clicks on the up/down arrows on the ~~heatmap~~ bucket bar.)

This is supposed to work even on PDF, and other lazy-rendering environments. 

However, it looks like this feature has been partially broken by one of the refactoring of the "focus" behavior, so now the the scrolling sometimes fails in lazy-rendered environments.

To reproduce:
 - Go to a PDF file (10 pages minimum)
 - Create an annotation at the bottom
 - Go back to to top
 - Refresh, redeploy
 - Click on the card

### LINKED ISSUE #1890: Fix up scrolling
Our scrolling tech is slightly broken in several ways. Such us:

 * Currently, there are two ways to trigger scrolling: by using the arrows on the bucket bar, and by clicking on annotation cards. However, the two things go down on different code paths, with slightly different bugs and features.
 * Some logic which is related to the handling of anchors (which play some part in scrolling) is placed in the bucket par, instead of other places where it belongs to.
 * Sometimes, we don't scroll far enough (to show a bit more, not just the line we want). (Arrows are OK, cards are not.)
 * Sometimes, scrolling on multi-paged documents doesn't work. (arrows are OK, cards are not.)

I am going to clean all this up.

### PR DESCRIPTION
**Pull request by csillag**
This is a refactoring of our scrolling code.

This PR contains all the non-controversial bits of #1899. 
Padded scrolling is completely removed in this version, so forking the upstream library is unnecessary.

This takes care of the cleanup of our own code; we can discuss how to best to the padded scrolling trick independently.

Text from the original PR:

   * * *

 * All scrolling-related code lives in the anchoring and highlight plugins; the bucket bar doesn't have to care for this any more
 * The two code-paths for triggering scrolling (bucket-bar arrows and annotation cards) have been unified.
 * ~~Padded scrolling (when we leave some space between the highlight and the edge of the viewport) is fully supported now in all cases.~~ Padded scrolling is removed
 * The whole madness of directions is gone now. ~~(Instead, I had to fork the jquery plugin responsible for the scrolling. It's a 4yo abandonware, so I hope that doesn't hurt as too much.)~~ 
 * Scrolling in multi-page documents (ie. pdf) is fixed.

Fixes #1873.
Fixes #1890.

### CODE REVIEW

**Comment by aron** [comment]
Great! Could you add some tests please.

**Comment by csillag** [comment]
> Could you add some tests please.

OK, so it's time to add tests for enhanced anchoring.

Before even hoping to test the scrolling functions added/changed here, we need a test stub/skeleton with some basic tests. I have added some *very* basic tests here: https://github.com/hypothesis/h/pull/1911 

Let's merge that first, and then I'll rebase this to that, and add test cases for the new functionality.

File: h/static/scripts/annotator/plugin/enhancedanchoring.coffee [hunk 1]
```diff
@@ -83,6 +89,37 @@ class Anchor
       # Kill the list if it's empty
       delete @anchoring.anchors[index] unless anchors.length
 
+  # Scroll to this anchor
+  scrollIntoView: ->
```
Comment (tilgovi) [inline h/static/scripts/annotator/plugin/enhancedanchoring.coffee]: Do you think this should be a method on the Anchor or would it be more useful for the Anchor to expose a commonAncestor Element or something like this? I'm just wondering because scrollIntoView is an Element API and rather than bubbling that API up to the Anchor maybe we should just expose an underlying Element.

Comment (csillag) [inline h/static/scripts/annotator/plugin/enhancedanchoring.coffee]: > Do you think this should be a method on the Anchor or would it be more useful for the Anchor to expose a commonAncestor Element or something like this? I'm just wondering because scrollIntoView is an Element API and rather than bubbling that API up to the Anchor maybe we should just expose an underlying Element.

It's more complicated than that. First, in this context, "scrolling" to an anchor might not actually mean physically scrolling a DOM element. It can involve completely different things, like calling arbitrary APIs of the underlying platform to access a specific location in the document. Furthermore, it's also possible that the Element (that we want to scroll to) might not even exist at this point. (If the anchor has not yet been realized, there is no highlight in the DOM, and maybe no relevant DOM at all.)

That's exactly why we have this API here. This wraps everything: do whatever we need to do in order to have the relevant part of the document rendered; identify the wanted element, create a highlight around it, *and then* scroll it into view.

**Comment by csillag** [comment]
> > Could you add some tests please.

> Before even hoping to test the scrolling functions added/changed here, we need a test stub/skeleton with some basic tests. I have added some *very* basic tests here: https://github.com/hypothesis/h/pull/1911 

So, basic tests have been merged to master.

Next step is to add test coverage to the two-phase anchoring stuff. I started that in https://github.com/hypothesis/h/pull/1927.

If we have that covered, then we can move on to testing the scrolling stuff.

**Comment by csillag** [comment]
I rebased this on top of current master, and now I have a travis bug that I can't seem to figure out. (It's probably the same issue that I also see [here](https://github.com/hypothesis/h/pull/1927#issuecomment-73616943).) Could someone point me out the problem in the travis report [here](https://travis-ci.org/hypothesis/h/builds/50133959)?

Thanks.

**Comment by csillag** [comment]
After rebasing on top of master (with @aron's fix), tests are green again.

**Comment by csillag** [comment]
> Could you add some tests please.

Now we have tests! 
Although it can probably be simplified a bit - suggestions are welcome.

File: tests/js/plugin/enhancedanchoring-test.coffee [hunk 2]
```diff
@@ -57,6 +59,11 @@ describe 'Annotator.Plugin.EnhancedAnchoring', ->
         anchor: anchor
         page: page
         removeFromDocument: sinon.spy()
+        scrollIntoView: sinon.spy ->
+          new Promise (resolve, reject) =>
+            setTimeout =>
+              @anchor.anchoring.document.setPageIndex @page
+              resolve()
```
Comment (aron) [inline tests/js/plugin/enhancedanchoring-test.coffee]: No need for the double arrows here, both objects are available to the scope.

```coffee
scrollIntoView: sinon.spy ->
  new Promise (resolve, reject) =>
    setTimeout =>
      anchor.anchoring.document.setPageIndex(page)
      resolve()
```

File: tests/js/plugin/enhancedanchoring-test.coffee [hunk 3]
```diff
@@ -219,16 +226,52 @@ describe 'Annotator.Plugin.EnhancedAnchoring', ->
...
+          @currentIndex = index
+
+          # Render the predicted next page
+          renderPage(this, prediction) unless @isPageMapped prediction
+
+        # Try to move where we need to be
+        if @isPageMapped index
+          onPageReady()
+        else
+          renderPage(this, index).then onPageReady
```
Comment (aron) [inline tests/js/plugin/enhancedanchoring-test.coffee]: There's way too much logic in here that's being tested. For the following tests we should be able to stub `isPageMapped` and `getPageIndex` to return explicit values and then assert `setPageIndex` or `scrollIntoView` is called with correct arguments.

File: tests/js/plugin/enhancedanchoring-test.coffee (hunk 2 above)
Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: Oh, right. Cleaned that up.

File: tests/js/plugin/enhancedanchoring-test.coffee (hunk 3 above)
Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: On 2015-02-11 10:43, Aron Carroll wrote:
> There's way too much logic in here that's being tested. For the
> following tests we should be able to stub |isPageMapped| and
> |getPageIndex| to return explicit values and then assert
> |setPageIndex| or |scrollIntoView| is called with correct arguments.

OK, how about now?

File: tests/js/plugin/enhancedanchoring-test.coffee [hunk 4]
```diff
@@ -634,3 +657,64 @@ describe 'Annotator.Plugin.EnhancedAnchoring', ->
...
+        am.document.currentIndex = 5  # We start from page 5
+        am.document.setPageIndex = sinon.spy (index) ->
+          am.document.currentIndex = index
+          if index is 9
+            renderPage am.document, 9
+            renderPage am.document, 10
+
+        # Now we trigger the actual action
+        anchor.scrollIntoView().then ->
+          assert.calledWith am.document.setPageIndex, 9
```
Comment (aron) [inline tests/js/plugin/enhancedanchoring-test.coffee]: Okay, so what I don't understand here is why `setPageIndex` needs to be a spy that renders the page when all we are doing is asserting that the method itself is called with the correct value. Is the following not equivalent?

```coffee
it 'scrolls right next to the wanted page (to get it rendered)', ->
   am = createAnchoringManagerAndLazyDocument()
   ann = createTestAnnotationForPages "a1", [10]
   anchor = am.createAnchor(ann, ann.target[0]).result

   am.document.currentIndex = 5  # We start from page 5
   am.document.setPageIndex = sandbox.stub()

   # Now we trigger the actual action
   anchor.scrollIntoView().then ->
     assert.calledWith am.document.setPageIndex, 9
```

File: tests/js/plugin/enhancedanchoring-test.coffee [hunk 5]
```diff
@@ -634,3 +657,64 @@ describe 'Annotator.Plugin.EnhancedAnchoring', ->
...
+      it 'scrolls to the wanted page, eventually', ->
+        am = createAnchoringManagerAndLazyDocument()
+        ann = createTestAnnotationForPages "a1", [10]
+        anchor = am.createAnchor(ann, ann.target[0]).result
+        am.document.currentIndex = 5  # We start from page 5
+        am.document.setPageIndex = sinon.spy (index) ->
+          am.document.currentIndex = index
+          if index is 9
+            renderPage am.document, 9
+            renderPage am.document, 10
```
Comment (aron) [inline tests/js/plugin/enhancedanchoring-test.coffee]: This looks like it's testing the wiring between the `setPageIndex` and the `renderPage` helper. These tests should only be validating the behaviour of the `scrollIntoView` method and that they call appropriate methods on dependencies. The behaviour of those dependencies should be tested elsewhere.

File: tests/js/plugin/enhancedanchoring-test.coffee (hunk 4 above)
Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: > Okay, so what I don't understand here is why `setPageIndex` needs to be a spy that renders the page when all we are doing is asserting that the method itself is called with the correct value.

If we don't render the page, `scrollIntoView()` will never complete. (Because it can only finish the scrolling when the wanted page is rendered.)

In the first test case, we can ignore that, but we need this code for the next two test case.

My thinking was that using the same preparatory steps for all 3 test cases improves the readability, and that's more important than the few extra lines.

Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: I simplified this test case in https://github.com/hypothesis/h/commit/b0d29a892a22ebd4c0e8ad9a9015561cecaf7b67.

File: tests/js/plugin/enhancedanchoring-test.coffee (hunk 5 above)
Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: > This looks like it's testing the wiring between the `setPageIndex` and the `renderPage` helper. 

Ummm... no, not really.

> These tests should only be validating the behaviour of the `scrollIntoView` method and that they call appropriate methods on dependencies.

That's exactly what we are doing; the challenge is that they can only perform all the required tasks if the other pieces cooperate. That's why we are mocking them.

Here is a detailed description of the process.

Our players are:
 * `Platform`: The piece of code responsible for rendering the document. Outside of our control. Example: PDF.js
 * `Document Access Strategy` (`docAccess` from now on): The piece of code responsible for interfacing with the specific platform. Implements the d-t-m interface. Examples: d-t-m, pdf-text-mapper
 * `Anchoring Manager`: this is the piece of code we are testing. Responsible for ... surprise: managing anchors.
  * `Application`: Gives high-level commands to the `Anchoring Manager`

Process (of scrolling to a virtual anchor, a.k.a. two-phase scrolling):
 * `Application` calls an Anchor's `scrollIntoView()` method, which is part of the `Anchoring Manager`.
 * The `scrollIntoView()` method recognizes that the wanted page is not rendered yet, so we need two-phase scrolling.
 * The `Anchoring Manager` instructs the `docAccess` to approach the wanted page (typically goes to the immediate neighboring page) - this is phase 1 of the scrolling
 * The `docAccess` requsts the `platform` to go to the specified page (using the platform-specific method to do so)
 * The `platform` goes to the wanted page, which is the neighbor of what we actually want
 * The `platform` takes a guess on the user's next move, and per-emtively renders the pages adjacent to the one currently displayed - including the page that we actually wanted.
 * The `docAccess`, which is monitoring the `platform` using whatever platform-spefic methods are available, recognizes that a new page has been rendered, and notifies the `Anchoring Manager` about this development.
 * In turn, the `Anchoring Manager` will realize all the anchors intersecting the given page, or in other words, it will create the highlights for it.
 * After the new highlights are created for the anchor that we want to scroll to, the `Anchoring Manager` remembers that it has a pending scroll on this anchor, which can be fully executed now, and so calls the `scrollIntoView()` method on the newly created highlight.
 * Then the highlight (which consists of actual DOM elements) will instruct the browser to scroll him into view (currently using the jquery scorllintoview plutin.)
 * The promise returned by the Anchor's `scrollIntoView()` method is resolved.

This is what happens.

In this test case, we are trying to test the `Anchoring Manager`'s behavior in this process.
To do so, we must play the part of the `Application`, and simulate/mock/stub the `Platform`, the `docAccess` and the `Highlight`.

And that's what we try to do.
 * `DummyDocumentAccess` is our fake `docAccess`.
 * The (manually triggered) `renderPage()`, `unrenderPage()` methods take on the role of the `platform`.

We only provide the parts that are required to fully exercise the code that must be tested in the `Anchoring Manager`.

Please advise me if you see any possibility to simplify the test, given these requirements.

Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: > This looks like it's testing the wiring between the `setPageIndex` and the `renderPage` helper. These tests should only be validating the behaviour of the `scrollIntoView` method and that they call appropriate methods on dependencies. The behaviour of those dependencies should be tested elsewhere.

To also give a shorter, more concrete answer:
 * The `Anchoring Manager` (which is the subject of this test) calls the `docAccess`'s `setPageIndex()` method as the first phase of the scrolling
 * To proceed to testing the second phase of the scrolling, the `docAccess` must get the `platform` render the page that we need.
 * That's why we are mocking the `setPageIndex()` method, and use the (fake) `renderPage()` method. What we are doing here is the bare minimum to short-circuit the system, so that the next function of the `Anchoring Manager` (which is rendering the highlight on the newly rendered page, and the scrolling to it) can be exercised.

Comment (csillag) [inline tests/js/plugin/enhancedanchoring-test.coffee]: > This looks like it's testing the wiring between the `setPageIndex` and the `renderPage` helper. These tests should only be validating the behaviour of the `scrollIntoView` method and that they call appropriate methods on dependencies. The behaviour of those dependencies should be tested elsewhere.

On a second look, there *was* a place of this code where we were testing the behavior of one of the helper functions. Now I removed that test case, and also the unnecessary line of helper code in https://github.com/hypothesis/h/commit/add512170c5ad71d2ad70172fc23175bf64986c6.

**Comment by csillag** [comment]
While waiting for the latest round of feedback from @aron, I have cleaned up some more small things at the tests.

**Comment by csillag** [comment]
Any further comment on this, anybody?

**Comment by aron** [comment]
:thumbsup:
