### PR TITLE
Fix real-time delete

### LINKED ISSUE #1928: Highlight is not removed from document when an annotation is deleted in a different window
Steps to reproduce:

1) Open two windows (**a** and **b**) with the sidebar open in a document.
2) Turn on "always on highlights" in **b** window.
3) Create an annotation in **a**, it should appear in **b**.
4) Delete the annotation in **a**.

Expected behaviour:

The annotation should be removed from the sidebar and the document in both **a** and **b**.

Actual behaviour:

The annotation is removed from both document and sidebar in **a**.
The annotation is removed from the sidebar in **b** but the highlight remains in the document.

### PR DESCRIPTION
**Pull request by csillag**
When receiving a real-time notification about the removal
of an annotation, we emit an annotationDeleted event,
so that all components can react.

Earlier, we emited this event simply with the Annotation
bject that arrived on the wire.

However, some components couldn't deal with this, because
they were expecting to see the 'real' Annotation object,
the ones they already knew about.

So now we do a lookup before emiting the event, and use
the locally found objects instead.

Fixes #1928.

   * * *

Please comment on this; I am not intimately familiar with how our custom 
cross-frame / client-server object persistence system life-cycle is supposed to work.

### CODE REVIEW

File: h/static/scripts/controllers.coffee [hunk 1]
```diff
@@ -48,7 +48,8 @@ class AppController
           annotationMapper.loadAnnotations data
         when 'delete'
           for annotation in data
-            $scope.$emit('annotationDeleted', annotation)
+            if a = threading.idTable[annotation.id]?.message
+              $scope.$emit('annotationDeleted', a)
```
Comment (gergely-ujvari) [inline h/static/scripts/controllers.coffee]: Heh..  I hope there is a nicer way.

Comment (gergely-ujvari) [inline h/static/scripts/controllers.coffee]: Like:
`annotationMapper.deleteAnnotation annotation` ?

Comment (csillag) [inline h/static/scripts/controllers.coffee]: Feel free to improve.

Comment (gergely-ujvari) [inline h/static/scripts/controllers.coffee]: No, annotationMapper does not work either.

Comment (aron) [inline h/static/scripts/controllers.coffee]: This is the right fix, and consistent with the how the controllers work at the moment.

`annotationMapper.deleteAnnotation` doesn't work either as that is intended to delete an annotation, this one has already been deleted.

Really though the streamer or a wrapper around the streamer should be looking up local annotations in the cache before they get to the controller. Threading should have a public `get()` method or the cache should be moved elsewhere as @tilgovi has already suggested. Lastly these events should be moved into a service so we don't have a million places with hard coded event strings.

This is all a bit much for a single PR, but I'd rather we didn't just add this here as is.

Comment (aron) [inline h/static/scripts/controllers.coffee]: Okay just chatted with @nickstenning about this. As this is consistent with the rest of the application controller lets get this fix in as is. Could you add a test to verify the fix and to prevent regressions, then we're good to go.

Comment (csillag) [inline h/static/scripts/controllers.coffee]: > Could you add a test to verify the fix and to prevent regressions

Umm.... I am trying to identify the relevant test suite, but until so far, I haven't found anything covering the part of AppController that is processing streamer messages.  (`streamer.onmessage`, `applyUpdates`, etc.)

Am I missing something here?

Comment (aron) [inline h/static/scripts/controllers.coffee]: This would be the place to add it: https://github.com/hypothesis/h/blob/master/tests/js/controllers-test.coffee#L60-L71

You'll need to mockup the threading service and call the `streamer.onmessage()` handler with appropriate data and assert the behaviours you're looking for, in this case that emit is called on scope, and the annotation is fetched from the threading service.

**Comment by csillag** [comment]
>  call the `streamer.onmessage()` handler with appropriate data

Ummm... could someone please show me how do I get access to the streamer service that is used by the `AppController`? Because using the obvious/naive method, ie. providing a fake implementation, `AppController` will have a copy of the `fakeStreamer` I originally provided, and not the exact same object. Therefore, I can't trivially access it's `onmessage()` method, added by the `AppController`. (Preliminary testing is [here](https://github.com/hypothesis/h/commit/4c9ab24b2e345631460e488ea811ba4dde40be8c#diff-5dbc072f84cdbca9f3692c8cb1960ad9R81).)

Alternatively, could someone please explain me the testing feature used [here](https://github.com/hypothesis/h/blob/4c9ab24b2e345631460e488ea811ba4dde40be8c/tests/js/streamer-service-test.coffee#L21) ? It seems to be doing something similar to what I need... just point me to the docs, please :)

**Comment by tilgovi** [comment]
https://code.angularjs.org/1.2.28/docs/api/ngMock/function/angular.mock.inject

**Comment by aron** [comment]
Docs: https://code.angularjs.org/1.2.26/docs/guide/unit-testing

onmessage is attached to the controller during construction, so you should be able to access it just fine after you have created the controller.

```coffee
controller = createController()
controller.onmessage(someData)
...
```

**Comment by csillag** [comment]
> onmessage is attached to the controller during construction, so you should be able to access it just fine after you have created the controller.

.... um ... so on `onMessages` is attached to the streamer, in the constructor of the AppController.

So if I use `controller = createController()` to create an `AppController`, `controller.onmessage` will be undefined, since `onmessage` is assigned as a property of the `streamer`, and not to the `AppController` itself. What am I missing here?

   * * *

Anyway, thanks for both links. Probably those will give me the answer - but not today.

**Comment by aron** [comment]
You also have references to the streamer (and every other dependency): https://github.com/hypothesis/h/blob/master/tests/js/controllers-test.coffee#L45-L49

**Comment by csillag** [comment]
That's exactly why I'm asking this; AppController uses a different object,
not that one. Maybe a copy. I tried...

**Comment by tilgovi** [comment]
Do you need help on this @csillag?

**Comment by csillag** [comment]
> Do you need help on this @csillag?

In fact I do. I could use some help with the testing. I'll comment on the (incomplete) test commit with an explanation.

**Comment by gergely-ujvari** [comment]
https://docs.angularjs.org/api/auto/service/$provide#value

**Comment by gergely-ujvari** [comment]
@csillag: you missed a `createController()` call from the test case.
Only the constructor of the controller patches the stream service! :smile:

**Comment by csillag** [comment]
See the debug output. It seems that we are running it...
2015.02.21. 13:41 ezt írta ("gergely-ujvari" <notifications@github.com>):

**Comment by csillag** [comment]
Oh, I see. It's running in a different test case.
2015.02.21. 13:41 ezt írta ("gergely-ujvari" <notifications@github.com>):

**Comment by csillag** [comment]
> Could you add a test to verify the fix and to prevent regressions, then we're good to go.

We have tests now!

**Comment by gergely-ujvari** [comment]
Okay, rebased, let's get this over with.
