### PR TITLE
Fix annotation thread collapsing

### LINKED ISSUE #2823: Comments should not be visable/unfurled by default
Comments on annotations are now vusible/unfurled by default. They should only be viewable once you have clicked the "x replies" link.

### PR DESCRIPTION
**Pull request by seanh**
This was broken by all the recent annotation directive refactoring:
annotation threads are now shown uncollapsed by default (should be
collapsed) and the buttons to collapse/uncollapse them do nothing.

vm/ctrl.editing became a method vm/ctrl.editing() but some code in the
link function wasn't updated.

This fixes them to be collapsed by default and gets the
collapse/uncollapse buttons working but I'm not sure if the collapse
behaviour is correct with nested threads.

Fixes #2823.

### CODE REVIEW

**Comment by seanh** [comment]
This is the basic fix, but I'm not sure that collapse/uncollapse of nested threads is working correctly. Would be nice to add a test too but this part of the code remains poorly understood and not very testable.

**Comment by seanh** [comment]
Actually I think the collapsing works fine, the UI is just quite unclear

**Comment by seanh** [comment]
Tests coming..

**Comment by seanh** [comment]
Ok, tests added.

Also note this commit: <https://github.com/hypothesis/h/commit/e58dc5d5f02538c7d3c84ed290ab47a4f2a31096>, I removed a `$watch()` that (as far as I can tell) isn't doing anything. This is not necessary to fix the bug at hand, but since I was understanding and writing unit tests for the link function and discovered this bit of weirdness, I removed it. This is the commit that the watch came from: <https://github.com/hypothesis/h/commit/9f94f2953b477ed889d59348deff2c4090aca27f>.

The tests that I've added are unit tests for the link function on its own (and I had to export the link function to make doing this reasonable), not unit tests for the directive as a whole. These tests wouldn't actually have caught the bug at hand, since the bug was caused by `AnnotationController`s interface changing and the link function not being updated, you would need tests that test `AnnotationController` and the link function together. These tests do serve to provide documentation for what the link function does though, and safety when making changes to the link function. I might have a look and see if I can write whole-directive tests for this too.

File: h/static/scripts/directive/annotation.js [hunk 1]
```diff
@@ -781,6 +781,49 @@ function AnnotationController(
...
+function link(scope, elem, attrs, controllers) {
+  var ctrl = controllers[0];
+  var thread = controllers[1];
+  var threadFilter = controllers[2];
+  var counter = controllers[3];
+
+  elem.on('keydown', ctrl.onKeydown);
+
+  // FIXME: Replace this counting code with something more sane.
+  if (counter !== null) {
```
Comment (robertknight) [inline h/static/scripts/directive/annotation.js]: Should be `if (counter) {`

File: h/static/scripts/directive/annotation.js [hunk 2]
```diff
@@ -781,6 +781,49 @@ function AnnotationController(
...
+        // Keep track of edits going on in the thread.
+        // This 'edit' count is for example to uncollapse a thread if one of
+        // the replies in the thread is currently being edited when the
+        // annotations are first rendered (this can happen when switching
+        // focus to a different group then back again, for example).
+        counter.count('edit', 1);
+
+        // Always show an annotation if it is being edited, even if there's an
+        // active search filter that does not match the annotation.
+        if ((thread !== null) && (threadFilter !== null)) {
```
Comment (robertknight) [inline h/static/scripts/directive/annotation.js]: Again, should test falsiness rather than against null

File: h/static/scripts/directive/test/annotation-test.js [hunk 3]
```diff
@@ -355,6 +355,202 @@ describe('annotation', function() {
...
+    }
+
+    function mockDeepCountController() {
+      return {
+        count: sinon.stub()
+      };
+    }
+
+    it('binds AnnotationController.onKeydown to "keydown"', function () {
+      var annotationController = mockAnnotationController();
```
Comment (robertknight) [inline h/static/scripts/directive/test/annotation-test.js]: There is an awful lot of boilerplate at the start of each of these tests. Can you try to extract it out and more DRY?

File: h/static/scripts/directive/annotation.js (hunk 1 above)
Comment (seanh) [inline h/static/scripts/directive/annotation.js]: This is pre-existing code (also the ones below), I didn't refactor it

File: h/static/scripts/directive/test/annotation-test.js (hunk 3 above)
Comment (seanh) [inline h/static/scripts/directive/test/annotation-test.js]: I've made them a little more DRY

File: h/static/scripts/directive/annotation.js (hunk 1 above)
Comment (seanh) [inline h/static/scripts/directive/annotation.js]: By the way it looks to me like this guard (and the one below it as well) is probably only hear because the required controllers are `null` when running the tests!

**Comment by nickstenning** [comment]
Could you add a CHANGES.txt entry for this?

**Comment by seanh** [comment]
Changelog added

**Comment by nickstenning** [comment]
LGTM. Great stuff.
